dev:
  http:
    port: "7010"
  db:
    postgres:
      host: "localhost"
      port: "5432"
      username: "root"
      db_name: "wb_orders"
      sslmode: "disable"
  nats:
    cluster: "test-cluster"
    port: "4222"
    client_id: "subscriber-dev"
    server: "localhost"


prod:
  http:
    port: "8010"
  db:
    postgres:
      host: "wb_orders_db"
      port: "5432"
      username: "root"
      db_name: "wb_orders"
      sslmode: "disable"
  nats:
    cluster: "test-cluster"
    port: "4222"
    client_id: "subscriber"
    server: "wb_nats_streaming"
